services:
  onepush-server:
    build:
      context: .
      target: ${TARGET}
      args:
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - 2002:${SERVER_PORT}
    # volumes:
    #   - ./:/app  # Commented out to prevent overwriting the built binary
    env_file:
      - .env